version: '3'

services:

  database:
    image: mongo
    container_name: database
    networks:
      - projectnet

  api:
    image: python:3.10
    container_name: api
    volumes:
      - ./api:/app
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python app.py"
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - projectnet

  client:
    image: python:3.10
    container_name: client
    volumes:
      - ./client:/client
    working_dir: /client
    command: bash -c "pip install requests && python client.py"
    depends_on:
      - api
    networks:
      - projectnet

networks:
  projectnet:
